In [6]:
import pandas as pd
property = pd.read_excel(r'../data/Property Dataset Final.xlsx')
property.head()

,PropertyID,PropertyTown,PropertyCounty,PropertyCurrentStatus,PropertyType,PropertyAreaOffice,PropertyOwningBody,PropertyLocalAuthorityArea,PropertySubType,PropertyStyle,YearOfConstruction,BedSpaces
0,U13210,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,4
1,U13211,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,4
2,U13217,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3
3,U13223,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3
4,U13224,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3

In [5]:
property = pd.read_csv(r'../data/Property Dataset Final_150.csv')
property.head()

,PropertyID,PropertyStreetCode,PropertyTown,PropertyCounty,PropertyCurrentStatus,PropertyType,PropertyAreaOffice,PropertyOwningBody,PropertyLocalAuthorityArea,PropertySubType,PropertyStyle,YearOfConstruction,BedSpaces
0,U13210,Ard Na Greine,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,4
1,U13211,Ard Na Greine,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,4
2,U13217,Ard Na Greine,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3
3,U13223,Ard Na Greine,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3
4,U13224,Ard Na Greine,Milltown,Co. Kerry,Occupied,Property,Gerard Deegan,Residential In Management,Kerry County,General Needs,Semi-detached House,2022,3